import logging
import json
from src.api.chat_ai import chat_with_ai
import uuid

JSON_FORMAT_PROMPT = """
You are a professional language learning curriculum designer.
A user wants a new roadmap. Your task is to generate a detailed roadmap based on their request.
You MUST respond with ONLY a valid JSON object. Do not include markdown (```json ... ```) or any text outside the JSON structure.

The JSON structure MUST be:
{
  "title": "Roadmap title based on user request",
  "description": "Short description of the roadmap (generated by AI)",
  "items": [
    {
      "item_id": "uuid_item_1",
      "title": "Item 1 Title",
      "description": "Item 1 Description",
      "order_index": 1,
      "estimated_time": 3,
      "type": "LESSON | PRACTICE | ASSESSMENT",
      "level": 1,
      "category": "GRAMMAR | VOCABULARY | PHONETICS | LISTENING",
      "difficulty": "easy | medium | hard",
      "exp_reward": 50,
      "content_id": "uuid_content_1"
    }
  ],
  "milestones": [
    {
      "milestone_id": "uuid_ms_1",
      "title": "Milestone 1 Title",
      "description": "Milestone 1 Description",
      "order_index": 1,
      "level": 1,
      "requirements": ["item_id_of_required_item"],
      "rewards": ["+50 XP", "New Badge"]
    }
  ],
  "guidances": [
    {
      "guidance_id": "uuid_guide_1",
      "item_id": "uuid_item_1",
      "stage": 1,
      "title": "Guidance Title (e.g., 'Tip')",
      "description": "Guidance description.",
      "tips": ["Tip 1", "Tip 2"],
      "estimated_time": 0,
      "order_index": 1
    }
  ],
  "resources": [
    {
      "resource_id": "uuid_res_1",
      "item_id": "uuid_item_1",
      "type": "BOOK | COURSE | VIDEO | URL",
      "title": "Resource Title",
      "description": "Resource Description",
      "url": "https://example.com/resource",
      "content_id": "",
      "duration": 0
    }
  ]
}

USER REQUEST: "{user_request}"
"""

async def generate_roadmap(
    language: str, prompt: str, as_user_specific: bool, user_profile: dict | None = None
):
    """
    Generate a learning roadmap by calling Gemini.
    """
    try:
        user_prompt = (
            f"Generate a detailed learning roadmap for {language}. Prompt: {prompt}"
        )
        if as_user_specific:
            user_prompt += " Tailored for user-specific needs."
            if user_profile and user_profile.get("recent_messages_summary"):
                user_prompt += (
                    f" User context: {user_profile.get('recent_messages_summary')}."
                )

        final_prompt = JSON_FORMAT_PROMPT.format(user_request=user_prompt)

        gemini_response_str, error = await chat_with_ai(
            final_prompt, history=[], language=language, user_profile=user_profile
        )

        if error:
            raise Exception(error)

        try:
            clean_json_str = gemini_response_str.strip().replace("```json", "").replace("```", "").strip()
            parsed_data = json.loads(clean_json_str)
        except json.JSONDecodeError as e:
            logging.error(f"Failed to parse JSON from Gemini: {e}")
            logging.error(f"Gemini response was: {gemini_response_str}")
            raise Exception(f"AI returned invalid JSON format. {e}")

        items = parsed_data.get("items", [])
        for item in items:
            item["item_id"] = item.get("item_id", str(uuid.uuid4()))

        milestones = parsed_data.get("milestones", [])
        for ms in milestones:
            ms["milestone_id"] = ms.get("milestone_id", str(uuid.uuid4()))

        guidances = parsed_data.get("guidances", [])
        for g in guidances:
            g["guidance_id"] = g.get("guidance_id", str(uuid.uuid4()))
            
        resources = parsed_data.get("resources", [])
        for r in resources:
            r["resource_id"] = r.get("resource_id", str(uuid.uuid4()))

        title = parsed_data.get("title", "AI Generated Roadmap")
        description = parsed_data.get("description", "A roadmap generated by MonkeyLingua AI.")

        total_items = len(items)
        completed_items = 0
        estimated_completion_time = sum(i.get("estimated_time", 1) for i in items)

        totals = {
            "title": title, # Thêm title/desc vào totals để trả về
            "description": description,
            "totalItems": total_items,
            "completedItems": completed_items,
            "estimatedCompletionTime": estimated_completion_time,
        }

        return description, items, milestones, guidances, resources, totals, None

    except Exception as e:
        logging.error(f"Roadmap generation failed: {str(e)}")
        return (
            "", [], [], [], [],
            {"totalItems": 0, "completedItems": 0, "estimatedCompletionTime": 0},
            str(e),
        )