package com.connectJPA.LinguaVietnameseApp.enums;

public enum ActivityType {
    VIDEO_WATCH, LOGIN, LESSON_COMPLETE, COURSE_ENROLLED, QUIZ_COMPLETE, GROUP_SESSION_JOINED, EXAM, START_LEARNING, LESSON_COMPLETION
}
