package com.connectJPA.LinguaVietnameseApp.enums;

public enum ActivityType {
    // Bổ sung để theo dõi thời gian
    LESSON_START,
    LESSON_END,
    CHAT_START,
    CHAT_END,
    GRAMMAR_EXERCISE,
    LESSON_COMPLETED,
    DAILY_CHALLENGE_COMPLETED,
    AI_CHAT,
    CHAT,CALL, QUIZ,

    // Bổ sung để đồng bộ từ service khác
    COURSE_ENROLL,
    BADGE_EARNED,
    TRANSACTION_SUCCESS,
    DAILY_CHALLENGE_COMPLETE_GRAMMAR_EXERCISE,VIDEO_WATCH, LOGIN, LESSON_COMPLETE, COURSE_ENROLLED, QUIZ_COMPLETE, GROUP_SESSION_JOINED, EXAM, START_LEARNING, LESSON_COMPLETION
}
