package com.connectJPA.LinguaVietnameseApp.enums;

public enum ChallengeType {
    LESSON_COMPLETED,
    SPEAKING_PRACTICE,
    LISTENING_PRACTICE,
    READING_COMPREHENSION,
    VOCABULARY_REVIEW,
    STREAK_MAINTAIN,
    EXP_EARNED,
    FRIEND_ADDED,
    REVIEW_SESSION,
    LEARNING_TIME,
    GIVE_ADMIRATION,
    SEND_MESSAGE,
    VIDEO_CALL, LESSON_COMPLETION
}