package com.connectJPA.LinguaVietnameseApp.enums;

public enum CriteriaType {
    FRIEND_ADDED,SEND_MESSAGE,GIVE_ADMIRATION,LEARNING_TIME, LESSONS_COMPLETED, LOGIN_STREAK, POINTS_EARNED,FRIENDS_MADE, DAILY_CHALLENGES_COMPLETED,EXP_EARNED
}