package com.connectJPA.LinguaVietnameseApp.enums;

public enum GoalType {
    COMMUNICATION, WORK, PERSONAL_DEVELOPMENT,CERTIFICATE , TRAVEL, CERTIFICATION, EXAM, CONVERSATION, BUSINESS, ACADEMIC, CULTURE, PROFICIENCY, OTHER, SKILL
}
