package com.connectJPA.LinguaVietnameseApp.enums;

public enum NotificationType {
    FLASHCARD_REMINDER, USER_REMINDER, MESSAGE, FRIEND_REQUEST, BADGE_UNLOCKED, LESSON_REMINDER, SYSTEM,STREAK_REMINDER, STREAK_RESET
}
