package com.connectJPA.LinguaVietnameseApp.enums;

public enum NotificationType {
    COURSE_APPROVAL_PENDING, AVATAR_UPDATE, DAILY_CHALLENGE_SUGGESTION, SYSTEM_TEST, VIP_EXTENDED, ADMIRE, TRANSACTION_FAILED, FLASHCARD_REMINDER, USER_REMINDER, MESSAGE, FRIEND_REQUEST, BADGE_UNLOCKED, LESSON_REMINDER, SYSTEM,STREAK_REMINDER, STREAK_RESET
}
