-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admirations
(
    admiration_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    sender_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT admirations_pkey PRIMARY KEY (admiration_id),
    CONSTRAINT uq_admiration_user_sender UNIQUE (user_id, sender_id)
);

CREATE TABLE IF NOT EXISTS public.badges
(
    badge_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    badge_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image_url character varying(255) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT badges_pkey PRIMARY KEY (badge_id),
    CONSTRAINT badges_badge_name_key UNIQUE (badge_name)
);

COMMENT ON TABLE public.badges
    IS 'Lưu trữ huy hiệu cho thành tích của người dùng';

CREATE TABLE IF NOT EXISTS public.character3ds
(
    character3d_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    character3d_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    model_url character varying(255) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT character3ds_pkey PRIMARY KEY (character3d_id),
    CONSTRAINT character3ds_character3d_name_key UNIQUE (character3d_name)
);

COMMENT ON TABLE public.character3ds
    IS 'Lưu trữ mô hình nhân vật 3D cho ảnh đại diện người dùng';

CREATE TABLE IF NOT EXISTS public.chat_messages
(
    chat_message_id uuid NOT NULL,
    content text COLLATE pg_catalog."default",
    media_url character varying(2083) COLLATE pg_catalog."default",
    message_type character varying(50) COLLATE pg_catalog."default",
    room_id uuid NOT NULL,
    sender_id uuid NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    sent_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    receiver_id uuid,
    CONSTRAINT unique_chat_message_id_sent_at PRIMARY KEY (chat_message_id, sent_at),
    CONSTRAINT uk_chat_message_id UNIQUE (chat_message_id)
);

COMMENT ON TABLE public.chat_messages
    IS 'Lưu trữ tin nhắn trò chuyện với phân vùng theo sent_at';

CREATE TABLE IF NOT EXISTS public.couples
(
    user1_id uuid NOT NULL,
    user2_id uuid NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    exploring_start timestamp with time zone,
    exploring_expires_at timestamp with time zone,
    couple_start_date timestamp with time zone,
    couple_score integer DEFAULT 0,
    CONSTRAINT couples_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.couples
    IS 'Lưu trữ các cặp người dùng để học tập theo cặp';

CREATE TABLE IF NOT EXISTS public.course_discounts
(
    discount_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    course_id uuid NOT NULL,
    discount_percentage integer NOT NULL,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT course_discounts_pkey PRIMARY KEY (discount_id)
);

COMMENT ON TABLE public.course_discounts
    IS 'Lưu trữ giảm giá khóa học';

CREATE TABLE IF NOT EXISTS public.course_enrollments
(
    enrollment_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    course_id uuid NOT NULL,
    user_id uuid NOT NULL,
    enrolled_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    CONSTRAINT course_enrollments_pkey PRIMARY KEY (enrollment_id)
);

COMMENT ON TABLE public.course_enrollments
    IS 'Lưu trữ đăng ký khóa học';

CREATE TABLE IF NOT EXISTS public.course_reviews
(
    review_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    course_id uuid NOT NULL,
    user_id uuid NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    rating numeric(3, 1) NOT NULL,
    comment text COLLATE pg_catalog."default",
    reviewed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT course_reviews_pkey PRIMARY KEY (review_id)
);

COMMENT ON TABLE public.course_reviews
    IS 'Lưu trữ đánh giá khóa học';

CREATE TABLE IF NOT EXISTS public.courses
(
    course_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    thumbnail_url character varying(255) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    creator_id uuid,
    difficulty_level character varying(50) COLLATE pg_catalog."default",
    approval_status character varying COLLATE pg_catalog."default",
    price numeric NOT NULL DEFAULT 0,
    CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

COMMENT ON TABLE public.courses
    IS 'Lưu trữ các khóa học';

CREATE TABLE IF NOT EXISTS public.daily_challenges
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    base_exp integer NOT NULL,
    difficulty character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    reward_coins integer DEFAULT 0,
    CONSTRAINT daily_challenges_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dating_invites
(
    invite_id uuid NOT NULL DEFAULT gen_random_uuid(),
    sender_id uuid NOT NULL,
    target_id uuid NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT dating_invites_pkey PRIMARY KEY (invite_id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    event_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    event_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    event_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    max_score integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT events_pkey PRIMARY KEY (event_id)
);

COMMENT ON TABLE public.events
    IS 'Lưu trữ thông tin về các sự kiện học tập';

CREATE TABLE IF NOT EXISTS public.flashcards
(
    flashcard_id uuid NOT NULL DEFAULT gen_random_uuid(),
    lesson_id uuid NOT NULL,
    user_id uuid,
    front text COLLATE pg_catalog."default",
    back text COLLATE pg_catalog."default",
    example_sentence text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    audio_url text COLLATE pg_catalog."default",
    tags text COLLATE pg_catalog."default",
    next_review_at timestamp with time zone,
    last_reviewed_at timestamp with time zone,
    interval_days integer DEFAULT 0,
    repetitions integer DEFAULT 0,
    ease_factor numeric DEFAULT 2.5,
    is_suspended boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT flashcards_pkey PRIMARY KEY (flashcard_id)
);

CREATE TABLE IF NOT EXISTS public.friendships
(
    user1_id uuid NOT NULL,
    user2_id uuid NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT friendships_pkey PRIMARY KEY (user1_id, user2_id)
);

COMMENT ON TABLE public.friendships
    IS 'Lưu trữ các mối quan hệ bạn bè và yêu cầu kết bạn';

CREATE TABLE IF NOT EXISTS public.grammar_examples
(
    id serial NOT NULL,
    lesson_id integer NOT NULL,
    sentence_en text COLLATE pg_catalog."default" NOT NULL,
    sentence_vi text COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT grammar_examples_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grammar_lessons
(
    id serial NOT NULL,
    topic_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    level character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT grammar_lessons_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grammar_topics
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT grammar_topics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.group_answers
(
    group_answer_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    group_session_id uuid,
    lesson_question_id uuid,
    user_id uuid,
    selected_option character varying(255) COLLATE pg_catalog."default",
    is_correct boolean NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    answered_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT group_answers_pkey PRIMARY KEY (group_answer_id)
);

COMMENT ON TABLE public.group_answers
    IS 'Lưu trữ câu trả lời trong phiên học nhóm';

CREATE TABLE IF NOT EXISTS public.group_sessions
(
    group_session_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_id uuid,
    room_id uuid,
    user_id uuid,
    is_deleted boolean NOT NULL DEFAULT false,
    started_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT group_sessions_pkey PRIMARY KEY (group_session_id)
);

COMMENT ON TABLE public.group_sessions
    IS 'Lưu trữ các phiên học nhóm';

CREATE TABLE IF NOT EXISTS public.interests
(
    interest_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    interest_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    icon character varying(50) COLLATE pg_catalog."default",
    color character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT interests_pkey PRIMARY KEY (interest_id),
    CONSTRAINT interests_interest_name_key UNIQUE (interest_name)
);

COMMENT ON TABLE public.interests
    IS 'Lưu trữ các sở thích để tùy chỉnh nội dung';

CREATE TABLE IF NOT EXISTS public.invalidated_tokens
(
    token character varying(512) COLLATE pg_catalog."default" NOT NULL,
    expiry_time timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT invalidated_tokens_pkey PRIMARY KEY (token)
);

COMMENT ON TABLE public.invalidated_tokens
    IS 'Lưu trữ các token xác thực đã bị vô hiệu hóa';

CREATE TABLE IF NOT EXISTS public.language_symbols
(
    id bigserial NOT NULL,
    language character varying(50) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    symbol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    pronunciation character varying(255) COLLATE pg_catalog."default",
    audio_url text COLLATE pg_catalog."default",
    video_url text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    examples jsonb,
    lesson_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT language_symbols_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.languages
(
    language_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    language_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT languages_pkey PRIMARY KEY (language_code),
    CONSTRAINT languages_language_name_key UNIQUE (language_name)
);

COMMENT ON TABLE public.languages
    IS 'Lưu trữ các ngôn ngữ được hỗ trợ bởi ứng dụng';

CREATE TABLE IF NOT EXISTS public.leaderboard_entries
(
    leaderboard_id uuid NOT NULL,
    user_id uuid NOT NULL,
    score integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT pk_leaderboard_entry PRIMARY KEY (leaderboard_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.leaderboards
(
    leaderboard_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    period character varying(50) COLLATE pg_catalog."default",
    tab character varying(50) COLLATE pg_catalog."default",
    snapshot_date date,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT leaderboards_pkey PRIMARY KEY (leaderboard_id)
);

COMMENT ON TABLE public.leaderboards
    IS 'Lưu trữ bảng xếp hạng';

CREATE TABLE IF NOT EXISTS public.lesson_categories
(
    lesson_category_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_category_name character varying(50) COLLATE pg_catalog."default",
    language_code character varying(2) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT lesson_categories_pkey PRIMARY KEY (lesson_category_id)
);

COMMENT ON TABLE public.lesson_categories
    IS 'Lưu trữ các danh mục bài học';

CREATE TABLE IF NOT EXISTS public.lesson_order_in_series
(
    lesson_id uuid NOT NULL,
    lesson_series_id uuid NOT NULL,
    order_index integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT lesson_order_in_series_pkey PRIMARY KEY (lesson_id, lesson_series_id)
);

COMMENT ON TABLE public.lesson_order_in_series
    IS 'Lưu trữ thứ tự bài học trong chuỗi';

CREATE TABLE IF NOT EXISTS public.lesson_progress
(
    lesson_id uuid NOT NULL,
    user_id uuid NOT NULL,
    score integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    max_score bigint,
    attempt_number bigint,
    needs_review boolean NOT NULL DEFAULT false,
    answers_json character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT lesson_progress_pkey PRIMARY KEY (lesson_id, user_id)
);

COMMENT ON TABLE public.lesson_progress
    IS 'Lưu trữ tiến độ bài học của người dùng';

CREATE TABLE IF NOT EXISTS public.lesson_progress_wrong_items
(
    lesson_id uuid NOT NULL,
    user_id uuid NOT NULL,
    lesson_question_id uuid NOT NULL,
    wrong_answer character varying(255) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    attempt_number integer NOT NULL DEFAULT 1,
    CONSTRAINT lesson_progress_wrong_items_pkey PRIMARY KEY (lesson_id, user_id, lesson_question_id, attempt_number)
);

COMMENT ON TABLE public.lesson_progress_wrong_items
    IS 'Lưu trữ câu trả lời sai cho bài học';

CREATE TABLE IF NOT EXISTS public.lesson_questions
(
    lesson_question_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_id uuid NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    question text COLLATE pg_catalog."default" NOT NULL,
    optiona character varying(255) COLLATE pg_catalog."default",
    optionb character varying(255) COLLATE pg_catalog."default",
    optionc character varying(255) COLLATE pg_catalog."default",
    optiond character varying(255) COLLATE pg_catalog."default",
    correct_option character varying(255) COLLATE pg_catalog."default",
    skill_type character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    question_type character varying(255) COLLATE pg_catalog."default",
    options_json character varying(255) COLLATE pg_catalog."default",
    media_url character varying(255) COLLATE pg_catalog."default",
    weight bigint NOT NULL DEFAULT 1,
    order_index bigint,
    explain_answer character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT lesson_questions_pkey PRIMARY KEY (lesson_question_id)
);

COMMENT ON TABLE public.lesson_questions
    IS 'Lưu trữ các câu hỏi bài học';

CREATE TABLE IF NOT EXISTS public.lesson_reviews
(
    review_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_id uuid NOT NULL,
    user_id uuid NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    rating numeric(3, 1) NOT NULL,
    comment text COLLATE pg_catalog."default",
    reviewed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT lesson_reviews_pkey PRIMARY KEY (review_id)
);

COMMENT ON TABLE public.lesson_reviews
    IS 'Lưu trữ đánh giá bài học';

CREATE TABLE IF NOT EXISTS public.lesson_series
(
    lesson_series_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_series_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT lesson_series_pkey PRIMARY KEY (lesson_series_id),
    CONSTRAINT lesson_series_lesson_series_name_key UNIQUE (lesson_series_name)
);

COMMENT ON TABLE public.lesson_series
    IS 'Lưu trữ các chuỗi bài học';

CREATE TABLE IF NOT EXISTS public.lesson_sub_categories
(
    lesson_sub_category_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_sub_category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lesson_category_id uuid,
    language_code character varying(2) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT lesson_sub_category_pkey PRIMARY KEY (lesson_sub_category_id),
    CONSTRAINT lesson_sub_category_lesson_sub_category_name_key UNIQUE (lesson_sub_category_name)
);

COMMENT ON TABLE public.lesson_sub_categories
    IS 'Lưu trữ các danh mục con của bài học';

CREATE TABLE IF NOT EXISTS public.lessons
(
    lesson_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    lesson_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    exp_reward integer NOT NULL,
    lesson_series_id uuid,
    lesson_category_id uuid,
    lesson_sub_category_id uuid,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    course_id uuid,
    lesson_type character varying(50) COLLATE pg_catalog."default",
    skill_types text COLLATE pg_catalog."default",
    is_free boolean NOT NULL DEFAULT false,
    "creator_id " uuid,
    description character varying(255) COLLATE pg_catalog."default",
    "difficulty_level " character varying COLLATE pg_catalog."default",
    duration_seconds bigint,
    pass_score_percent bigint,
    certificate_code character varying(255) COLLATE pg_catalog."default",
    allowed_retake_count bigint NOT NULL DEFAULT 0,
    shuffle_questions boolean NOT NULL DEFAULT false,
    CONSTRAINT lessons_pkey PRIMARY KEY (lesson_id),
    CONSTRAINT lessons_lesson_name_key UNIQUE (lesson_name)
);

COMMENT ON TABLE public.lessons
    IS 'Lưu trữ các bài học, mỗi bài học có thể thuộc về một khóa học (course), chuỗi bài học (series), danh mục hoặc danh mục con';

CREATE TABLE IF NOT EXISTS public.message_reactions
(
    reaction_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    chat_message_id uuid NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL,
    reaction character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT message_reactions_pkey PRIMARY KEY (reaction_id)
);

COMMENT ON TABLE public.message_reactions
    IS 'Lưu trữ phản ứng với tin nhắn';

CREATE TABLE IF NOT EXISTS public.message_translations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    chat_message_id uuid NOT NULL,
    target_lang character varying(8) COLLATE pg_catalog."default",
    translated_text text COLLATE pg_catalog."default",
    provider character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT message_translations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    payload character varying(255) COLLATE pg_catalog."default",
    read boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

COMMENT ON TABLE public.notifications
    IS 'Lưu trữ thông báo của người dùng';

CREATE TABLE IF NOT EXISTS public.permissions
(
    permission_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id),
    CONSTRAINT permissions_name_key UNIQUE (name)
);

COMMENT ON TABLE public.permissions
    IS 'Lưu trữ quyền cho các vai trò';

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    is_revoked boolean NOT NULL DEFAULT false,
    expires_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    device_id character varying(255) COLLATE pg_catalog."default",
    ip character varying(255) COLLATE pg_catalog."default",
    user_agent character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT refreshtokens_pkey PRIMARY KEY (id),
    CONSTRAINT refreshtokens_token_key UNIQUE (token)
);

COMMENT ON TABLE public.refresh_tokens
    IS 'Lưu trữ các refresh token của người dùng';

CREATE TABLE IF NOT EXISTS public.review_reactions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    review_id uuid NOT NULL,
    user_id uuid NOT NULL,
    reaction smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT review_reactions_pkey PRIMARY KEY (id),
    CONSTRAINT review_reactions_review_id_user_id_key UNIQUE (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.roadmap_guidance
(
    guidance_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    item_id uuid NOT NULL,
    stage character varying(100) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    tips text[] COLLATE pg_catalog."default",
    estimated_time integer,
    order_index integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT roadmap_guidance_pkey PRIMARY KEY (guidance_id)
);

CREATE TABLE IF NOT EXISTS public.roadmap_items
(
    item_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    roadmap_id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default",
    level integer,
    estimated_time integer,
    order_index integer,
    category character varying(100) COLLATE pg_catalog."default",
    difficulty character varying(20) COLLATE pg_catalog."default",
    exp_reward integer DEFAULT 0,
    content_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT roadmap_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.roadmap_milestones
(
    milestone_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    roadmap_id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    level integer,
    requirements text[] COLLATE pg_catalog."default",
    rewards text[] COLLATE pg_catalog."default",
    order_index integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT roadmap_milestones_pkey PRIMARY KEY (milestone_id)
);

CREATE TABLE IF NOT EXISTS public.roadmap_resources
(
    resource_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    item_id uuid NOT NULL,
    type character varying(20) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    content_id uuid,
    duration integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    CONSTRAINT roadmap_resources_pkey PRIMARY KEY (resource_id)
);

CREATE TABLE IF NOT EXISTS public.roadmap_suggestions
(
    suggestion_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    roadmap_id uuid NOT NULL,
    item_id uuid,
    suggested_order_index integer,
    reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    applied boolean DEFAULT false,
    CONSTRAINT roadmap_suggestions_pkey PRIMARY KEY (suggestion_id)
);

CREATE TABLE IF NOT EXISTS public.roadmaps
(
    roadmap_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    language_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    total_items integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT roadmaps_pkey PRIMARY KEY (roadmap_id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    permission_id uuid NOT NULL,
    role_id uuid NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (permission_id, role_id)
);

COMMENT ON TABLE public.role_permissions
    IS 'Lưu trữ quyền của vai trò';

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

COMMENT ON TABLE public.roles
    IS 'Lưu trữ vai trò cho quyền của người dùng';

CREATE TABLE IF NOT EXISTS public.room_members
(
    room_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    joined_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT room_members_pkey PRIMARY KEY (room_id, user_id)
);

COMMENT ON TABLE public.room_members
    IS 'Lưu trữ thành viên của phòng';

CREATE TABLE IF NOT EXISTS public.rooms
(
    room_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    room_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    creator_id uuid,
    max_members integer NOT NULL,
    purpose character varying(50) COLLATE pg_catalog."default",
    room_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    topic character varying(255) COLLATE pg_catalog."default",
    nick_name_in_rom character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT rooms_pkey PRIMARY KEY (room_id)
);

COMMENT ON TABLE public.rooms
    IS 'Lưu trữ các phòng trò chuyện để giao tiếp';

CREATE TABLE IF NOT EXISTS public.transactions
(
    transaction_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    amount double precision NOT NULL,
    description text COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    provider character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VNPAY'::character varying,
    currency character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USD'::character varying,
    wallet_id uuid,
    sender_id uuid,
    receiver_id uuid,
    original_transaction_id uuid,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_TYPE'::character varying,
    payment_gateway_transaction_id character varying(255) COLLATE pg_catalog."default",
    idempotency_key character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
    CONSTRAINT transactions_idempotency_key_key UNIQUE (idempotency_key)
);

COMMENT ON TABLE public.transactions
    IS 'Lưu trữ các giao dịch của người dùng';

CREATE TABLE IF NOT EXISTS public.user_auth_accounts
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    provider character varying(50) COLLATE pg_catalog."default" NOT NULL,
    provider_user_id character varying(255) COLLATE pg_catalog."default",
    verified boolean NOT NULL DEFAULT false,
    is_primary boolean NOT NULL DEFAULT false,
    linked_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_auth_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT uq_provider_user UNIQUE (provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS public.user_badges
(
    badge_id uuid NOT NULL,
    user_id uuid NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_badges_pkey PRIMARY KEY (badge_id, user_id)
);

COMMENT ON TABLE public.user_badges
    IS 'Lưu trữ huy hiệu của người dùng';

CREATE TABLE IF NOT EXISTS public.user_certificates
(
    user_id uuid NOT NULL,
    certificate character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at time with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_certificates_pkey PRIMARY KEY (user_id, certificate)
);

CREATE TABLE IF NOT EXISTS public.user_daily_challenges
(
    user_id uuid NOT NULL,
    challenge_id uuid NOT NULL,
    assigned_date timestamp with time zone NOT NULL,
    stack integer NOT NULL,
    exp_reward integer NOT NULL,
    is_completed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    reward_coins integer DEFAULT 0,
    progress integer,
    assigned_at timestamp without time zone,
    completed_at timestamp without time zone,
    CONSTRAINT pk_user_daily_challenges PRIMARY KEY (user_id, challenge_id, assigned_date, stack)
);

CREATE TABLE IF NOT EXISTS public.user_events
(
    event_id uuid NOT NULL,
    user_id uuid NOT NULL,
    score integer NOT NULL DEFAULT 0,
    rank integer,
    participated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_completed boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_events_pkey PRIMARY KEY (event_id, user_id)
);

COMMENT ON TABLE public.user_events
    IS 'Lưu trữ điểm số và trạng thái tham gia sự kiện của người dùng';

CREATE TABLE IF NOT EXISTS public.user_fcm_tokens
(
    user_fcm_token_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    fcm_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_fcm_tokens_pkey PRIMARY KEY (user_fcm_token_id),
    CONSTRAINT user_fcm_tokens_fcm_token_key UNIQUE (fcm_token)
);

COMMENT ON TABLE public.user_fcm_tokens
    IS 'Lưu trữ token FCM của người dùng cho thông báo đẩy';

CREATE TABLE IF NOT EXISTS public.user_goals
(
    goal_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default",
    certificate character varying(100) COLLATE pg_catalog."default",
    target_score integer,
    target_skill character varying(50) COLLATE pg_catalog."default",
    custom_description text COLLATE pg_catalog."default",
    goal_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    target_proficiency character varying(50) COLLATE pg_catalog."default",
    target_date timestamp with time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_goals_pkey PRIMARY KEY (goal_id)
);

COMMENT ON TABLE public.user_goals
    IS 'Lưu trữ mục tiêu học tập của người dùng';

CREATE TABLE IF NOT EXISTS public.user_interests
(
    user_id uuid NOT NULL,
    interest_id uuid NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_interests_pkey PRIMARY KEY (user_id, interest_id)
);

COMMENT ON TABLE public.user_interests
    IS 'Lưu trữ sở thích của người dùng';

CREATE TABLE IF NOT EXISTS public.user_languages
(
    language_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    proficiency_level character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_languages_pkey PRIMARY KEY (language_code, user_id)
);

COMMENT ON TABLE public.user_languages
    IS 'Lưu trữ sở thích ngôn ngữ của người dùng';

CREATE TABLE IF NOT EXISTS public.user_learning_activities
(
    activity_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    activity_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    target_id uuid,
    duration_in_seconds integer,
    details text COLLATE pg_catalog."default",
    related_entity_id uuid,
    CONSTRAINT user_learning_activities_pkey PRIMARY KEY (activity_id)
);

COMMENT ON TABLE public.user_learning_activities
    IS 'Lưu trữ hoạt động học tập để đánh giá mức độ siêng năng';

CREATE TABLE IF NOT EXISTS public.user_media
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    media_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default",
    file_path text COLLATE pg_catalog."default",
    file_url text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_media_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_memorizations
(
    memorization_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    content_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content_id uuid,
    note_text text COLLATE pg_catalog."default",
    is_favorite boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_memorizations_pkey PRIMARY KEY (memorization_id)
);

CREATE TABLE IF NOT EXISTS public.user_reminders
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    target_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    target_id uuid,
    title character varying(255) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    reminder_time timestamp with time zone NOT NULL,
    reminder_date timestamp with time zone,
    repeat_type character varying(50) COLLATE pg_catalog."default",
    enabled boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_reminders_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.user_reminders
    IS 'Lưu trữ nhắc nhở của người dùng';

CREATE TABLE IF NOT EXISTS public.user_roadmaps
(
    user_roadmap_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    roadmap_id uuid NOT NULL,
    user_id uuid NOT NULL,
    current_level integer DEFAULT 0,
    target_level integer,
    target_proficiency character varying(50) COLLATE pg_catalog."default",
    estimated_completion_time integer,
    completed_items integer DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    language character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT user_roadmaps_pkey PRIMARY KEY (user_roadmap_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    role_id uuid NOT NULL,
    user_id uuid NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id)
);

COMMENT ON TABLE public.user_roles
    IS 'Lưu trữ vai trò của người dùng';

CREATE TABLE IF NOT EXISTS public.user_series_progress
(
    series_id uuid NOT NULL,
    user_id uuid NOT NULL,
    current_index integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    started_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT user_series_progress_pkey PRIMARY KEY (series_id, user_id)
);

COMMENT ON TABLE public.user_series_progress
    IS 'Lưu trữ tiến độ chuỗi bài học của người dùng';

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    fullname character varying(255) COLLATE pg_catalog."default",
    nickname character varying(50) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    avatar_url character varying(255) COLLATE pg_catalog."default",
    character3d_id uuid,
    native_language_code character varying(2) COLLATE pg_catalog."default",
    country character varying(50) COLLATE pg_catalog."default",
    level integer NOT NULL DEFAULT 1,
    exp integer NOT NULL DEFAULT 0,
    streak integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    learning_pace character varying(50) COLLATE pg_catalog."default",
    age_range character varying(50) COLLATE pg_catalog."default",
    proficiency character varying(50) COLLATE pg_catalog."default",
    last_active_at timestamp with time zone,
    bio character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_key UNIQUE (phone)
);

COMMENT ON TABLE public.users
    IS 'Lưu trữ thông tin tài khoản người dùng';

CREATE TABLE IF NOT EXISTS public.video_call_participants
(
    video_call_id uuid NOT NULL,
    user_id uuid NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT video_call_participants_pkey PRIMARY KEY (video_call_id, user_id)
);

COMMENT ON TABLE public.video_call_participants
    IS 'Lưu trữ người tham gia cuộc gọi video';

CREATE TABLE IF NOT EXISTS public.video_calls
(
    video_call_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    room_id uuid,
    caller_id uuid,
    callee_id uuid,
    video_call_type character varying(50) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'initiated'::character varying,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    duration interval GENERATED ALWAYS AS ((end_time - start_time)) STORED,
    quality_metrics jsonb,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT video_calls_pkey PRIMARY KEY (video_call_id)
);

COMMENT ON TABLE public.video_calls
    IS 'Lưu trữ các cuộc gọi video';

CREATE TABLE IF NOT EXISTS public.video_reactions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    video_id uuid NOT NULL,
    user_id uuid NOT NULL,
    reaction smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT video_reactions_pkey PRIMARY KEY (id),
    CONSTRAINT video_reactions_video_id_user_id_key UNIQUE (video_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.video_reviews
(
    review_id uuid NOT NULL DEFAULT gen_random_uuid(),
    video_id uuid NOT NULL,
    user_id uuid NOT NULL,
    rating integer,
    content text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT video_reviews_pkey PRIMARY KEY (review_id)
);

CREATE TABLE IF NOT EXISTS public.video_subtitles
(
    video_subtitle_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    video_id uuid NOT NULL,
    language_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    subtitle_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT video_subtitles_pkey PRIMARY KEY (video_subtitle_id)
);

COMMENT ON TABLE public.video_subtitles
    IS 'Lưu trữ phụ đề video cho các ngôn ngữ khác nhau';

CREATE TABLE IF NOT EXISTS public.videos
(
    video_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    video_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    original_subtitle_url character varying(255) COLLATE pg_catalog."default",
    lesson_id uuid NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT videos_pkey PRIMARY KEY (video_id)
);

COMMENT ON TABLE public.videos
    IS 'Lưu trữ thông tin video cho các bài học';

CREATE TABLE IF NOT EXISTS public.wallets
(
    wallet_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    balance numeric(19, 4) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp with time zone,
    CONSTRAINT wallets_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT wallets_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT fk_chat_messages_room FOREIGN KEY (room_id)
    REFERENCES public.rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.couples
    ADD CONSTRAINT fk_couples_user1 FOREIGN KEY (user1_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.couples
    ADD CONSTRAINT fk_couples_user2 FOREIGN KEY (user2_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_discounts
    ADD CONSTRAINT fk_course_discounts_course FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_enrollments
    ADD CONSTRAINT fk_course_enrollments_course FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_enrollments
    ADD CONSTRAINT fk_course_enrollments_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_reviews
    ADD CONSTRAINT fk_course_reviews_course FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_reviews
    ADD CONSTRAINT fk_course_reviews_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.course_reviews
    ADD CONSTRAINT fk_course_reviews_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT fk_course_creator FOREIGN KEY (creator_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT fk_course_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT fk_friendships_user1 FOREIGN KEY (user1_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT fk_friendships_user2 FOREIGN KEY (user2_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grammar_examples
    ADD CONSTRAINT grammar_examples_lesson_id_fkey FOREIGN KEY (lesson_id)
    REFERENCES public.grammar_lessons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grammar_lessons
    ADD CONSTRAINT grammar_lessons_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.grammar_topics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.group_answers
    ADD CONSTRAINT fk_group_answers_question FOREIGN KEY (lesson_question_id)
    REFERENCES public.lesson_questions (lesson_question_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.group_answers
    ADD CONSTRAINT fk_group_answers_session FOREIGN KEY (group_session_id)
    REFERENCES public.group_sessions (group_session_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.group_answers
    ADD CONSTRAINT fk_group_answers_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.group_sessions
    ADD CONSTRAINT fk_group_sessions_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.group_sessions
    ADD CONSTRAINT fk_group_sessions_room FOREIGN KEY (room_id)
    REFERENCES public.rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.group_sessions
    ADD CONSTRAINT fk_group_sessions_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.leaderboard_entries
    ADD CONSTRAINT fk_leaderboard FOREIGN KEY (leaderboard_id)
    REFERENCES public.leaderboards (leaderboard_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.leaderboard_entries
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lesson_categories
    ADD CONSTRAINT fk_lesson_category_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lesson_order_in_series
    ADD CONSTRAINT fk_lesson_order_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_order_in_series
    ADD CONSTRAINT fk_lesson_order_series FOREIGN KEY (lesson_series_id)
    REFERENCES public.lesson_series (lesson_series_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress
    ADD CONSTRAINT fk_lesson_progress_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress
    ADD CONSTRAINT fk_lesson_progress_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress_wrong_items
    ADD CONSTRAINT fk_lesson_progress_wrong_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress_wrong_items
    ADD CONSTRAINT fk_lesson_progress_wrong_question FOREIGN KEY (lesson_question_id)
    REFERENCES public.lesson_questions (lesson_question_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress_wrong_items
    ADD CONSTRAINT fk_lesson_progress_wrong_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_questions
    ADD CONSTRAINT fk_lesson_questions_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lesson_questions
    ADD CONSTRAINT fk_lesson_questions_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_reviews
    ADD CONSTRAINT fk_lesson_reviews_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lesson_reviews
    ADD CONSTRAINT fk_lesson_reviews_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_reviews
    ADD CONSTRAINT fk_lesson_reviews_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_series
    ADD CONSTRAINT fk_lesson_series_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lesson_sub_categories
    ADD CONSTRAINT fk_sub_category_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lesson_sub_categories
    ADD CONSTRAINT fk_sub_category_to_category FOREIGN KEY (lesson_category_id)
    REFERENCES public.lesson_categories (lesson_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lesson_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lesson_to_category FOREIGN KEY (lesson_category_id)
    REFERENCES public.lesson_categories (lesson_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lesson_to_course FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lesson_to_series FOREIGN KEY (lesson_series_id)
    REFERENCES public.lesson_series (lesson_series_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lesson_to_sub_category FOREIGN KEY (lesson_sub_category_id)
    REFERENCES public.lesson_sub_categories (lesson_sub_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.message_reactions
    ADD CONSTRAINT fk_message_reactions_message FOREIGN KEY (chat_message_id, sent_at)
    REFERENCES public.chat_messages (chat_message_id, sent_at) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.message_reactions
    ADD CONSTRAINT fk_message_reactions_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.message_translations
    ADD CONSTRAINT message_translations_chat_message_id_fkey FOREIGN KEY (chat_message_id)
    REFERENCES public.chat_messages (chat_message_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk_notifications_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT fk_refreshtokens_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.review_reactions
    ADD CONSTRAINT review_reactions_review_id_fkey FOREIGN KEY (review_id)
    REFERENCES public.video_reviews (review_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roadmap_guidance
    ADD CONSTRAINT fk_roadmap_guidance_item FOREIGN KEY (item_id)
    REFERENCES public.roadmap_items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roadmap_items
    ADD CONSTRAINT fk_roadmap_items_roadmap FOREIGN KEY (roadmap_id)
    REFERENCES public.roadmaps (roadmap_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roadmap_milestones
    ADD CONSTRAINT fk_roadmap_milestones_roadmap FOREIGN KEY (roadmap_id)
    REFERENCES public.roadmaps (roadmap_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roadmap_resources
    ADD CONSTRAINT fk_roadmap_resources_item FOREIGN KEY (item_id)
    REFERENCES public.roadmap_items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roadmap_suggestions
    ADD CONSTRAINT fk_roadmap_suggestions_roadmap FOREIGN KEY (roadmap_id)
    REFERENCES public.roadmaps (roadmap_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_roadmap_suggestions_roadmap_id
    ON public.roadmap_suggestions(roadmap_id);


ALTER TABLE IF EXISTS public.roadmap_suggestions
    ADD CONSTRAINT fk_roadmap_suggestions_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_roadmap_suggestions_user_id
    ON public.roadmap_suggestions(user_id);


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
    REFERENCES public.permissions (permission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.room_members
    ADD CONSTRAINT fk_room_members_room FOREIGN KEY (room_id)
    REFERENCES public.rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.room_members
    ADD CONSTRAINT fk_room_members_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rooms
    ADD CONSTRAINT fk_room_creator FOREIGN KEY (creator_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_transactions_original FOREIGN KEY (original_transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_transactions_receiver FOREIGN KEY (receiver_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_transactions_sender FOREIGN KEY (sender_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_transactions_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_transactions_wallet FOREIGN KEY (wallet_id)
    REFERENCES public.wallets (wallet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_auth_accounts
    ADD CONSTRAINT fk_user_auth_accounts_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_badges
    ADD CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id)
    REFERENCES public.badges (badge_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_badges
    ADD CONSTRAINT fk_user_badges_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_certificates
    ADD CONSTRAINT fk_user_certificates_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_certificates_user_id
    ON public.user_certificates(user_id);


ALTER TABLE IF EXISTS public.user_daily_challenges
    ADD CONSTRAINT fk_challenge FOREIGN KEY (challenge_id)
    REFERENCES public.daily_challenges (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_daily_challenges
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_events
    ADD CONSTRAINT fk_user_events_event FOREIGN KEY (event_id)
    REFERENCES public.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_events
    ADD CONSTRAINT fk_user_events_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_fcm_tokens
    ADD CONSTRAINT fk_user_fcm_tokens_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_goals
    ADD CONSTRAINT fk_user_goals_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_goals
    ADD CONSTRAINT fk_user_goals_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_interests
    ADD CONSTRAINT fk_user_interests_interest FOREIGN KEY (interest_id)
    REFERENCES public.interests (interest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_interests
    ADD CONSTRAINT fk_user_interests_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_languages
    ADD CONSTRAINT fk_user_languages_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_languages
    ADD CONSTRAINT fk_user_languages_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_learning_activities
    ADD CONSTRAINT fk_user_learning_activities_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_memorizations
    ADD CONSTRAINT fk_user_memorizations_event FOREIGN KEY (content_id)
    REFERENCES public.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.user_memorizations
    ADD CONSTRAINT fk_user_memorizations_lesson FOREIGN KEY (content_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.user_memorizations
    ADD CONSTRAINT fk_user_memorizations_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_memorizations
    ADD CONSTRAINT fk_user_memorizations_video FOREIGN KEY (content_id)
    REFERENCES public.videos (video_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.user_reminders
    ADD CONSTRAINT fk_user_reminders_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_roadmaps
    ADD CONSTRAINT fk_user_roadmaps_roadmap FOREIGN KEY (roadmap_id)
    REFERENCES public.roadmaps (roadmap_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roadmaps
    ADD CONSTRAINT fk_user_roadmaps_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_series_progress
    ADD CONSTRAINT fk_user_series_progress_series FOREIGN KEY (series_id)
    REFERENCES public.lesson_series (lesson_series_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_series_progress
    ADD CONSTRAINT fk_user_series_progress_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_user_character FOREIGN KEY (character3d_id)
    REFERENCES public.character3ds (character3d_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_user_native_language FOREIGN KEY (native_language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.video_call_participants
    ADD CONSTRAINT fk_video_call_participants_call FOREIGN KEY (video_call_id)
    REFERENCES public.video_calls (video_call_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.video_call_participants
    ADD CONSTRAINT fk_video_call_participants_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.video_calls
    ADD CONSTRAINT fk_video_calls_callee FOREIGN KEY (callee_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.video_calls
    ADD CONSTRAINT fk_video_calls_caller FOREIGN KEY (caller_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.video_calls
    ADD CONSTRAINT fk_video_calls_room FOREIGN KEY (room_id)
    REFERENCES public.rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.video_reactions
    ADD CONSTRAINT video_reactions_video_id_fkey FOREIGN KEY (video_id)
    REFERENCES public.videos (video_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.video_reviews
    ADD CONSTRAINT video_reviews_video_id_fkey FOREIGN KEY (video_id)
    REFERENCES public.videos (video_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.video_subtitles
    ADD CONSTRAINT fk_video_subtitles_language FOREIGN KEY (language_code)
    REFERENCES public.languages (language_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.video_subtitles
    ADD CONSTRAINT fk_video_subtitles_video FOREIGN KEY (video_id)
    REFERENCES public.videos (video_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.videos
    ADD CONSTRAINT fk_videos_lesson FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (lesson_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;