# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import learning_service_pb2 as learning__service__pb2


class LearningServiceStub(object):
    """=====================
    Core LearningService
    =====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpeechToText = channel.unary_unary(
                '/learning.LearningService/SpeechToText',
                request_serializer=learning__service__pb2.SpeechRequest.SerializeToString,
                response_deserializer=learning__service__pb2.SpeechResponse.FromString,
                )
        self.GenerateTts = channel.unary_unary(
                '/learning.LearningService/GenerateTts',
                request_serializer=learning__service__pb2.TtsRequest.SerializeToString,
                response_deserializer=learning__service__pb2.TtsResponse.FromString,
                )
        self.CheckPronunciation = channel.unary_unary(
                '/learning.LearningService/CheckPronunciation',
                request_serializer=learning__service__pb2.PronunciationRequest.SerializeToString,
                response_deserializer=learning__service__pb2.PronunciationResponse.FromString,
                )
        self.StreamPronunciation = channel.stream_stream(
                '/learning.LearningService/StreamPronunciation',
                request_serializer=learning__service__pb2.PronunciationChunk.SerializeToString,
                response_deserializer=learning__service__pb2.PronunciationChunkResponse.FromString,
                )
        self.CheckSpelling = channel.unary_unary(
                '/learning.LearningService/CheckSpelling',
                request_serializer=learning__service__pb2.SpellingRequest.SerializeToString,
                response_deserializer=learning__service__pb2.SpellingResponse.FromString,
                )
        self.CheckTranslation = channel.unary_unary(
                '/learning.LearningService/CheckTranslation',
                request_serializer=learning__service__pb2.CheckTranslationRequest.SerializeToString,
                response_deserializer=learning__service__pb2.CheckTranslationResponse.FromString,
                )
        self.CheckWritingWithImage = channel.unary_unary(
                '/learning.LearningService/CheckWritingWithImage',
                request_serializer=learning__service__pb2.WritingImageRequest.SerializeToString,
                response_deserializer=learning__service__pb2.WritingImageResponse.FromString,
                )
        self.ChatWithAI = channel.unary_unary(
                '/learning.LearningService/ChatWithAI',
                request_serializer=learning__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=learning__service__pb2.ChatResponse.FromString,
                )
        self.Translate = channel.unary_unary(
                '/learning.LearningService/Translate',
                request_serializer=learning__service__pb2.TranslateRequest.SerializeToString,
                response_deserializer=learning__service__pb2.TranslateResponse.FromString,
                )
        self.GenerateImage = channel.unary_unary(
                '/learning.LearningService/GenerateImage',
                request_serializer=learning__service__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GenerateImageResponse.FromString,
                )
        self.GenerateText = channel.unary_unary(
                '/learning.LearningService/GenerateText',
                request_serializer=learning__service__pb2.GenerateTextRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GenerateTextResponse.FromString,
                )
        self.GeneratePassage = channel.unary_unary(
                '/learning.LearningService/GeneratePassage',
                request_serializer=learning__service__pb2.GeneratePassageRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GeneratePassageResponse.FromString,
                )
        self.CreateOrUpdateRoadmap = channel.unary_unary(
                '/learning.LearningService/CreateOrUpdateRoadmap',
                request_serializer=learning__service__pb2.RoadmapRequest.SerializeToString,
                response_deserializer=learning__service__pb2.RoadmapResponse.FromString,
                )
        self.CreateOrUpdateRoadmapDetailed = channel.unary_unary(
                '/learning.LearningService/CreateOrUpdateRoadmapDetailed',
                request_serializer=learning__service__pb2.RoadmapDetailedRequest.SerializeToString,
                response_deserializer=learning__service__pb2.RoadmapDetailedResponse.FromString,
                )
        self.AnalyzeCourseQuality = channel.unary_unary(
                '/learning.LearningService/AnalyzeCourseQuality',
                request_serializer=learning__service__pb2.CourseQualityRequest.SerializeToString,
                response_deserializer=learning__service__pb2.CourseQualityResponse.FromString,
                )
        self.RefundDecision = channel.unary_unary(
                '/learning.LearningService/RefundDecision',
                request_serializer=learning__service__pb2.RefundDecisionRequest.SerializeToString,
                response_deserializer=learning__service__pb2.RefundDecisionResponse.FromString,
                )
        self.FindMatch = channel.unary_unary(
                '/learning.LearningService/FindMatch',
                request_serializer=learning__service__pb2.FindMatchRequest.SerializeToString,
                response_deserializer=learning__service__pb2.FindMatchResponse.FromString,
                )
        self.AnalyzeReviewQuality = channel.unary_unary(
                '/learning.LearningService/AnalyzeReviewQuality',
                request_serializer=learning__service__pb2.ReviewQualityRequest.SerializeToString,
                response_deserializer=learning__service__pb2.ReviewQualityResponse.FromString,
                )
        self.GenerateLanguageQuiz = channel.unary_unary(
                '/learning.LearningService/GenerateLanguageQuiz',
                request_serializer=learning__service__pb2.QuizGenerationRequest.SerializeToString,
                response_deserializer=learning__service__pb2.QuizGenerationResponse.FromString,
                )


class LearningServiceServicer(object):
    """=====================
    Core LearningService
    =====================
    """

    def SpeechToText(self, request, context):
        """--- Speech & Audio ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPronunciation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPronunciation(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSpelling(self, request, context):
        """--- Text-based ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTranslation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckWritingWithImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatWithAI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Translate(self, request, context):
        """✅ New rpc for translation (used by Java client)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImage(self, request, context):
        """--- Content Generation ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePassage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrUpdateRoadmap(self, request, context):
        """--- Personalized Learning ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrUpdateRoadmapDetailed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCourseQuality(self, request, context):
        """--- System-level / analytics ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeReviewQuality(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateLanguageQuiz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpeechToText': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=learning__service__pb2.SpeechRequest.FromString,
                    response_serializer=learning__service__pb2.SpeechResponse.SerializeToString,
            ),
            'GenerateTts': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTts,
                    request_deserializer=learning__service__pb2.TtsRequest.FromString,
                    response_serializer=learning__service__pb2.TtsResponse.SerializeToString,
            ),
            'CheckPronunciation': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPronunciation,
                    request_deserializer=learning__service__pb2.PronunciationRequest.FromString,
                    response_serializer=learning__service__pb2.PronunciationResponse.SerializeToString,
            ),
            'StreamPronunciation': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPronunciation,
                    request_deserializer=learning__service__pb2.PronunciationChunk.FromString,
                    response_serializer=learning__service__pb2.PronunciationChunkResponse.SerializeToString,
            ),
            'CheckSpelling': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSpelling,
                    request_deserializer=learning__service__pb2.SpellingRequest.FromString,
                    response_serializer=learning__service__pb2.SpellingResponse.SerializeToString,
            ),
            'CheckTranslation': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTranslation,
                    request_deserializer=learning__service__pb2.CheckTranslationRequest.FromString,
                    response_serializer=learning__service__pb2.CheckTranslationResponse.SerializeToString,
            ),
            'CheckWritingWithImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckWritingWithImage,
                    request_deserializer=learning__service__pb2.WritingImageRequest.FromString,
                    response_serializer=learning__service__pb2.WritingImageResponse.SerializeToString,
            ),
            'ChatWithAI': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatWithAI,
                    request_deserializer=learning__service__pb2.ChatRequest.FromString,
                    response_serializer=learning__service__pb2.ChatResponse.SerializeToString,
            ),
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=learning__service__pb2.TranslateRequest.FromString,
                    response_serializer=learning__service__pb2.TranslateResponse.SerializeToString,
            ),
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=learning__service__pb2.GenerateImageRequest.FromString,
                    response_serializer=learning__service__pb2.GenerateImageResponse.SerializeToString,
            ),
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=learning__service__pb2.GenerateTextRequest.FromString,
                    response_serializer=learning__service__pb2.GenerateTextResponse.SerializeToString,
            ),
            'GeneratePassage': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePassage,
                    request_deserializer=learning__service__pb2.GeneratePassageRequest.FromString,
                    response_serializer=learning__service__pb2.GeneratePassageResponse.SerializeToString,
            ),
            'CreateOrUpdateRoadmap': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdateRoadmap,
                    request_deserializer=learning__service__pb2.RoadmapRequest.FromString,
                    response_serializer=learning__service__pb2.RoadmapResponse.SerializeToString,
            ),
            'CreateOrUpdateRoadmapDetailed': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdateRoadmapDetailed,
                    request_deserializer=learning__service__pb2.RoadmapDetailedRequest.FromString,
                    response_serializer=learning__service__pb2.RoadmapDetailedResponse.SerializeToString,
            ),
            'AnalyzeCourseQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCourseQuality,
                    request_deserializer=learning__service__pb2.CourseQualityRequest.FromString,
                    response_serializer=learning__service__pb2.CourseQualityResponse.SerializeToString,
            ),
            'RefundDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundDecision,
                    request_deserializer=learning__service__pb2.RefundDecisionRequest.FromString,
                    response_serializer=learning__service__pb2.RefundDecisionResponse.SerializeToString,
            ),
            'FindMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FindMatch,
                    request_deserializer=learning__service__pb2.FindMatchRequest.FromString,
                    response_serializer=learning__service__pb2.FindMatchResponse.SerializeToString,
            ),
            'AnalyzeReviewQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeReviewQuality,
                    request_deserializer=learning__service__pb2.ReviewQualityRequest.FromString,
                    response_serializer=learning__service__pb2.ReviewQualityResponse.SerializeToString,
            ),
            'GenerateLanguageQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLanguageQuiz,
                    request_deserializer=learning__service__pb2.QuizGenerationRequest.FromString,
                    response_serializer=learning__service__pb2.QuizGenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'learning.LearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LearningService(object):
    """=====================
    Core LearningService
    =====================
    """

    @staticmethod
    def SpeechToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/SpeechToText',
            learning__service__pb2.SpeechRequest.SerializeToString,
            learning__service__pb2.SpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateTts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/GenerateTts',
            learning__service__pb2.TtsRequest.SerializeToString,
            learning__service__pb2.TtsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckPronunciation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/CheckPronunciation',
            learning__service__pb2.PronunciationRequest.SerializeToString,
            learning__service__pb2.PronunciationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPronunciation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/learning.LearningService/StreamPronunciation',
            learning__service__pb2.PronunciationChunk.SerializeToString,
            learning__service__pb2.PronunciationChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckSpelling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/CheckSpelling',
            learning__service__pb2.SpellingRequest.SerializeToString,
            learning__service__pb2.SpellingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckTranslation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/CheckTranslation',
            learning__service__pb2.CheckTranslationRequest.SerializeToString,
            learning__service__pb2.CheckTranslationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckWritingWithImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/CheckWritingWithImage',
            learning__service__pb2.WritingImageRequest.SerializeToString,
            learning__service__pb2.WritingImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChatWithAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/ChatWithAI',
            learning__service__pb2.ChatRequest.SerializeToString,
            learning__service__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/Translate',
            learning__service__pb2.TranslateRequest.SerializeToString,
            learning__service__pb2.TranslateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/GenerateImage',
            learning__service__pb2.GenerateImageRequest.SerializeToString,
            learning__service__pb2.GenerateImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/GenerateText',
            learning__service__pb2.GenerateTextRequest.SerializeToString,
            learning__service__pb2.GenerateTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GeneratePassage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/GeneratePassage',
            learning__service__pb2.GeneratePassageRequest.SerializeToString,
            learning__service__pb2.GeneratePassageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrUpdateRoadmap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/CreateOrUpdateRoadmap',
            learning__service__pb2.RoadmapRequest.SerializeToString,
            learning__service__pb2.RoadmapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrUpdateRoadmapDetailed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/CreateOrUpdateRoadmapDetailed',
            learning__service__pb2.RoadmapDetailedRequest.SerializeToString,
            learning__service__pb2.RoadmapDetailedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeCourseQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/AnalyzeCourseQuality',
            learning__service__pb2.CourseQualityRequest.SerializeToString,
            learning__service__pb2.CourseQualityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefundDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/RefundDecision',
            learning__service__pb2.RefundDecisionRequest.SerializeToString,
            learning__service__pb2.RefundDecisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/FindMatch',
            learning__service__pb2.FindMatchRequest.SerializeToString,
            learning__service__pb2.FindMatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeReviewQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/AnalyzeReviewQuality',
            learning__service__pb2.ReviewQualityRequest.SerializeToString,
            learning__service__pb2.ReviewQualityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateLanguageQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learning.LearningService/GenerateLanguageQuiz',
            learning__service__pb2.QuizGenerationRequest.SerializeToString,
            learning__service__pb2.QuizGenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
