FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY LinguaVietnameseApp/.mvn .mvn
COPY LinguaVietnameseApp/mvnw .
COPY LinguaVietnameseApp/pom.xml .
COPY LinguaVietnameseApp/src ./src

RUN sed -i 's/\r$//' mvnw && chmod +x mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine AS runtime

WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/app.jar"]