name: Deploy Spring Boot Backend to Render

on:
  push:
    paths:
      - "LinguaVietnameseApp/LinguaVietnameseApp/**"   # chỉ chạy khi thay đổi code trong thư mục này
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Spring Boot JAR
        working-directory: backend-java
        run: mvn clean package -DskipTests

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_JAVA_DEPLOY_HOOK }}
        run: |
          echo "🚀 Triggering Render deploy..."
          curl -X POST "$RENDER_DEPLOY_HOOK"
          echo "✅ Deploy triggered successfully."
